apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: gepide
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-port-9093
      protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP