- name: Deploy Swagger UI
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: swagger-ui
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: swagger-ui
        template:
          metadata:
            labels:
              app: swagger-ui
          spec:
            containers:
              - name: swagger-ui
                image: swaggerapi/swagger-ui
                ports:
                  - containerPort: 8080
                env:
                  - name: SWAGGER_JSON
                    value: /app/swagger.json
                volumeMounts:
                  - name: swagger-volume
                    mountPath: /app
            volumes:
              - name: swagger-volume
                hostPath:
                  path: ./swagger
